# Generated by Django 2.2.3 on 2019-07-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('S', 'success'), ('P', 'primary'), ('I', 'info'), ('W', 'warning'), ('D', 'danger'), ('A', 'dark'), ('E', 'secondary'), ('L', 'light')], default='P', max_length=1),
        ),
    ]
