# Generated by Django 2.2.3 on 2019-07-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20190726_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('T', 'mobile-alt'), ('B', 'book'), ('M', 'music'), ('C', 'fa-car'), ('H', 'home'), ('A', 'basketball-ball'), ('E', 'headphones'), ('D', 'baby-carriage')], default='B', max_length=1),
        ),
    ]
