# Generated by Django 2.2.3 on 2019-07-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20190728_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='item_pictures'),
        ),
    ]
