# Generated by Django 2.2.3 on 2019-07-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_auto_20190729_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, default='item_pictures/default.jpg', null=True, upload_to='item_pictures'),
        ),
    ]
