# Generated by Django 2.2.3 on 2019-07-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_itemrental_fulfilled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrental',
            old_name='start_date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='itemrental',
            name='end_date',
        ),
    ]
