# Generated by Django 2.2.3 on 2019-08-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_auto_20190731_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('T', 'mobile-alt'), ('B', 'book'), ('M', 'music'), ('C', 'car'), ('H', 'home'), ('A', 'basketball-ball'), ('E', 'headphones'), ('D', 'baby-carriage')], default='B', max_length=1),
        ),
    ]
